### ISSUE TITLE
Improvements to the import system

### ISSUE THREAD

**Issue by RafaelPalomar** [MONK-system/system#39]
The import process is not designed as expected exactly.

 `The Nihon-Kohden files` section should list all the `.mwf` files in a given folder (remember that the CNS will drop all the files in a specific folder). We want that the screen lists the files in that folder and allow import from there. Once a file is imported (it should be moved to an internal folder), which will produce that the table does not show the file anymore (we don't care about files already imported).

### TODO

- [ ] Remove import button from Nihon-Khoden files section
- [ ] Add functionality to configure the directory that the system will 'scan' for `.mwf` files and show in the Nihon-Kohden files section table. The table should either have a refresh button or update the table whenever the directory in question changes. 
- [ ] Add function to configure the internal directory the system will use to keep the imported files (this should be in the admin menu)
- [ ] Add a menu bar item called Import that will take the user to Nihon-Kohden files
- [ ] Import can be either to a personal area of a given user or to a project. These options should be available when importing.

**Comment by RafaelPalomar** [comment]
This is superseded by monk-system/system#44
